DEBUG="FALSE"
configuration_base="./"
ctrl="controller"
serv="service"
impl="*impl" # impl="*impl"
rep="repository"
pkg=""
model="model"
emodel=""

ctrlExt="Controller"
servExt="Service"
implExt="ServiceImpl"
repExt="Repository"
modelExt=""
FORCE="FALSE"
template="templates/"
forceConfig=""
HELP="FALSE"
supp="FALSE"