CREATE TABLE PUBLIC.BASE (
	"DATE" DATE,
	NAME VARCHAR(255),
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.BASEDATE (
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.BASEDATE_EVENT (
	BASEDATE_ID BIGINT NOT NULL,
	EVENTS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.BASE_LISTEITEM (
	BASE_ID BIGINT NOT NULL,
	WILL_ID BIGINT NOT NULL,
	LEARN_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC."DAY" (
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.DAY_LISTEITEM (
	DAY_ID BIGINT NOT NULL,
	TODOLISTALL_ID BIGINT NOT NULL,
	TODOLIST_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.EVENT (
	DATEDEBUT TIMESTAMP,
	DATEFIN TIMESTAMP,
	NOTES VARCHAR(255),
	TITLE VARCHAR(255),
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.GOAL (
	TITLE VARCHAR(255),
	WHY VARCHAR(255),
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.GOAL_LISTEITEM (
	GOAL_ID BIGINT NOT NULL,
	HOW_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.IDS (
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.LISTEITEM (
	NAME VARCHAR(255),
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC."MONTH" (
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.MONTH_WEEK (
	MONTH_ID BIGINT NOT NULL,
	WEEKS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.ROLE (
	ROLENAME VARCHAR(255),
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.SESSION (
	"DATE" DATE,
	NAME VARCHAR(255),
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.SESSION_GOAL (
	SESSION_ID BIGINT NOT NULL,
	GOALS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.SESSION_MONTH (
	SESSION_ID BIGINT NOT NULL,
	MONTHS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.SESSION_TASK (
	SESSION_ID BIGINT NOT NULL,
	TASKS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.TASK (
	NAME VARCHAR(255),
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.TOKEN (
	TOKEN VARCHAR(255),
	VALABLE BOOLEAN,
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC."USER" (
	ID BIGINT NOT NULL,
	EMAIL VARCHAR(115),
	FIRST_NAME VARCHAR(75),
	LAST_NAME VARCHAR(80),
	PASSWORD VARCHAR(64),
	USERNAME VARCHAR(65),
	ROLE_ID BIGINT,
	USERINFO_ID BIGINT,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.USERINFO (
	ID BIGINT NOT NULL,
	SESSCUR_ID BIGINT,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.USERINFO_SESSION (
	USERINFO_ID BIGINT NOT NULL,
	SESS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.USER_TOKEN (
	USER_ID BIGINT NOT NULL,
	TOKENS_ID BIGINT NOT NULL
);

CREATE TABLE PUBLIC.WEEK (
	ID BIGINT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.WEEK_DAY (
	WEEK_ID BIGINT NOT NULL,
	DAYS_ID BIGINT NOT NULL
);

ALTER TABLE PUBLIC.BASE
	ADD FOREIGN KEY (ID) 
	REFERENCES IDS (ID);



ALTER TABLE PUBLIC.BASEDATE
	ADD FOREIGN KEY (ID) 
	REFERENCES BASE (ID);



ALTER TABLE PUBLIC.BASEDATE_EVENT
	ADD FOREIGN KEY (BASEDATE_ID) 
	REFERENCES BASEDATE (ID);

ALTER TABLE PUBLIC.BASEDATE_EVENT
	ADD FOREIGN KEY (EVENTS_ID) 
	REFERENCES EVENT (ID);



ALTER TABLE PUBLIC.BASE_LISTEITEM
	ADD FOREIGN KEY (BASE_ID) 
	REFERENCES BASE (ID);

ALTER TABLE PUBLIC.BASE_LISTEITEM
	ADD FOREIGN KEY (LEARN_ID) 
	REFERENCES LISTEITEM (ID);

ALTER TABLE PUBLIC.BASE_LISTEITEM
	ADD FOREIGN KEY (WILL_ID) 
	REFERENCES LISTEITEM (ID);



ALTER TABLE PUBLIC."DAY"
	ADD FOREIGN KEY (ID) 
	REFERENCES BASEDATE (ID);



ALTER TABLE PUBLIC.DAY_LISTEITEM
	ADD FOREIGN KEY (DAY_ID) 
	REFERENCES "DAY" (ID);

ALTER TABLE PUBLIC.DAY_LISTEITEM
	ADD FOREIGN KEY (TODOLISTALL_ID) 
	REFERENCES LISTEITEM (ID);

ALTER TABLE PUBLIC.DAY_LISTEITEM
	ADD FOREIGN KEY (TODOLIST_ID) 
	REFERENCES LISTEITEM (ID);



ALTER TABLE PUBLIC.EVENT
	ADD FOREIGN KEY (ID) 
	REFERENCES IDS (ID);



ALTER TABLE PUBLIC.GOAL
	ADD FOREIGN KEY (ID) 
	REFERENCES IDS (ID);



ALTER TABLE PUBLIC.GOAL_LISTEITEM
	ADD FOREIGN KEY (GOAL_ID) 
	REFERENCES GOAL (ID);

ALTER TABLE PUBLIC.GOAL_LISTEITEM
	ADD FOREIGN KEY (HOW_ID) 
	REFERENCES LISTEITEM (ID);



ALTER TABLE PUBLIC.LISTEITEM
	ADD FOREIGN KEY (ID) 
	REFERENCES IDS (ID);



ALTER TABLE PUBLIC."MONTH"
	ADD FOREIGN KEY (ID) 
	REFERENCES BASEDATE (ID);



ALTER TABLE PUBLIC.MONTH_WEEK
	ADD FOREIGN KEY (MONTH_ID) 
	REFERENCES "MONTH" (ID);

ALTER TABLE PUBLIC.MONTH_WEEK
	ADD FOREIGN KEY (WEEKS_ID) 
	REFERENCES WEEK (ID);



ALTER TABLE PUBLIC.ROLE
	ADD FOREIGN KEY (ID) 
	REFERENCES IDS (ID);



ALTER TABLE PUBLIC.SESSION
	ADD FOREIGN KEY (ID) 
	REFERENCES IDS (ID);



ALTER TABLE PUBLIC.SESSION_GOAL
	ADD FOREIGN KEY (GOALS_ID) 
	REFERENCES GOAL (ID);

ALTER TABLE PUBLIC.SESSION_GOAL
	ADD FOREIGN KEY (SESSION_ID) 
	REFERENCES SESSION (ID);



ALTER TABLE PUBLIC.SESSION_MONTH
	ADD FOREIGN KEY (MONTHS_ID) 
	REFERENCES "MONTH" (ID);

ALTER TABLE PUBLIC.SESSION_MONTH
	ADD FOREIGN KEY (SESSION_ID) 
	REFERENCES SESSION (ID);



ALTER TABLE PUBLIC.SESSION_TASK
	ADD FOREIGN KEY (SESSION_ID) 
	REFERENCES SESSION (ID);

ALTER TABLE PUBLIC.SESSION_TASK
	ADD FOREIGN KEY (TASKS_ID) 
	REFERENCES TASK (ID);



ALTER TABLE PUBLIC.TASK
	ADD FOREIGN KEY (ID) 
	REFERENCES IDS (ID);



ALTER TABLE PUBLIC."USER"
	ADD FOREIGN KEY (ROLE_ID) 
	REFERENCES ROLE (ID);

ALTER TABLE PUBLIC."USER"
	ADD FOREIGN KEY (USERINFO_ID) 
	REFERENCES USERINFO (ID);



ALTER TABLE PUBLIC.USERINFO_SESSION
	ADD FOREIGN KEY (SESS_ID) 
	REFERENCES SESSION (ID);

ALTER TABLE PUBLIC.USERINFO_SESSION
	ADD FOREIGN KEY (USERINFO_ID) 
	REFERENCES USERINFO (ID);



ALTER TABLE PUBLIC.USER_TOKEN
	ADD FOREIGN KEY (TOKENS_ID) 
	REFERENCES TOKEN (ID);

ALTER TABLE PUBLIC.USER_TOKEN
	ADD FOREIGN KEY (USER_ID) 
	REFERENCES "USER" (ID);



ALTER TABLE PUBLIC.WEEK
	ADD FOREIGN KEY (ID) 
	REFERENCES BASEDATE (ID);



ALTER TABLE PUBLIC.WEEK_DAY
	ADD FOREIGN KEY (DAYS_ID) 
	REFERENCES "DAY" (ID);

ALTER TABLE PUBLIC.WEEK_DAY
	ADD FOREIGN KEY (WEEK_ID) 
	REFERENCES WEEK (ID);



CREATE INDEX PUBLIC.SYS_IDX_FK1P2IPWMGG3W9M6Q8IKVVVPG0X_12242 ON PUBLIC.MONTH_WEEK (MONTH_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK2Q7NJK5O2O8KDHMHH7UPGQLWJ_12268 ON PUBLIC.SESSION_TASK (TASKS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK2SVWNFHDRBBC625KURDI9FY15_12179 ON PUBLIC.BASE_LISTEITEM (BASE_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK52UPN39EQO9ALKYVTQMSK74HK_12256 ON PUBLIC.SESSION_GOAL (SESSION_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK5LTR776FVK4R0NSN4V8S5D3S5_12171 ON PUBLIC.BASE (ID);

CREATE INDEX PUBLIC.SYS_IDX_FK618AEO209JCXE59HYI1M94NNC_12203 ON PUBLIC.DAY_LISTEITEM (TODOLISTALL_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK6CJFICNLGX8594HI9TUAS1YLL_12297 ON PUBLIC.USERINFO_SESSION (USERINFO_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK7OXN6MF1WP0LBT1S09ICPVBXD_12213 ON PUBLIC.DAY_LISTEITEM (TODOLIST_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK9I76RXLX77X1KRXU8O6O7CGX8_12249 ON PUBLIC.SESSION (ID);

CREATE INDEX PUBLIC.SYS_IDX_FK9JV5K3VECSHMMW5KNQAB4I305_12308 ON PUBLIC.WEEK_DAY (WEEK_ID);

CREATE INDEX PUBLIC.SYS_IDX_FK9N3FX3UK4JQYXYQTHEQFOXNWD_12184 ON PUBLIC.BASE_LISTEITEM (LEARN_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKAKESO1W60NDTY097C44LOQ073_12276 ON PUBLIC.TASK (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKBA9AH9XFM0BLNVXREOU41TYFK_12238 ON PUBLIC.MONTH_WEEK (WEEKS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKBIH44S21A8352CY06APTWDOMU_12264 ON PUBLIC.SESSION_MONTH (SESSION_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKCJ0W38U6YNT3WP79GJ6D1NJNI_12272 ON PUBLIC.SESSION_TASK (SESSION_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKD33SXMSRWAIBCSBHLRWYDQJ4E_12235 ON PUBLIC."MONTH" (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKD4BSHF0X1EIA74IAE3CBMYU0V_12304 ON PUBLIC.WEEK_DAY (DAYS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKEHKX0MXW1I2L96L5U8C6JLVTP_12293 ON PUBLIC.USERINFO_SESSION (SESS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKEOH8N0F6UP7JJ573RLQAOKJEP_12196 ON PUBLIC.BASEDATE_EVENT (BASEDATE_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKFHJ9FGJYRBOWKMOY72WX2LB8_12301 ON PUBLIC.WEEK (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKGDBKA671I4UKB4K03ECWQS2S6_12232 ON PUBLIC.LISTEITEM (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKGS59T65D14TC8XYNUJRI8BBIN_12189 ON PUBLIC.BASEDATE (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKI0Y1WQ070O3WWNVIC5CKL78KK_12200 ON PUBLIC."DAY" (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKJB1EHURQYKP493HQUCHWQNBHC_12228 ON PUBLIC.GOAL_LISTEITEM (GOAL_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKJGP8S9J0FVW987WJ04OB8PD5R_12221 ON PUBLIC.GOAL (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKJRT56VVA5Q617KGNE8ARF06T2_12260 ON PUBLIC.SESSION_MONTH (MONTHS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKLH7U0KPJ1Y4NHESFCVAXNRFMM_12174 ON PUBLIC.BASE_LISTEITEM (WILL_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKMOVHHB4H5UJE64TKEG7UEOBRQ_12208 ON PUBLIC.DAY_LISTEITEM (DAY_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKMTU0RPDIFCE8DHWXMB88SBX2P_12218 ON PUBLIC.EVENT (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKMX3VDIU7JVWDWARGS09XSVYE9_12285 ON PUBLIC.USER_TOKEN (USER_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKO8PL6FVVBOSPE9UHQG0E1DN5J_10280 ON PUBLIC."USER" (ROLE_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKOL71AKE6NGOPPAKFFO9V1QHG1_12252 ON PUBLIC.SESSION_GOAL (GOALS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKP7SYU9F63WJXHSW0FKBBY4SIR_12192 ON PUBLIC.BASEDATE_EVENT (EVENTS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKR4JE2XBFA8A09SF5WUVYWFE0V_12246 ON PUBLIC.ROLE (ID);

CREATE INDEX PUBLIC.SYS_IDX_FKR6J1UCC2V9OK5J03YSXMX32U1_10283 ON PUBLIC."USER" (USERINFO_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKRWAQWRL6WLE4TILWW5QWH0RCL_12281 ON PUBLIC.USER_TOKEN (TOKENS_ID);

CREATE INDEX PUBLIC.SYS_IDX_FKSBH1VOIFTP0JXW9BYS4VNOEFR_12224 ON PUBLIC.GOAL_LISTEITEM (HOW_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10092_10093 ON PUBLIC."USER" (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10184_10185 ON PUBLIC.ROLE (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10230_10231 ON PUBLIC.TOKEN (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_10246_10247 ON PUBLIC.USERINFO (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12013_12014 ON PUBLIC.BASE (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12024_12025 ON PUBLIC.BASEDATE (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12033_12034 ON PUBLIC."DAY" (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12044_12045 ON PUBLIC.EVENT (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12048_12049 ON PUBLIC.GOAL (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12057_12058 ON PUBLIC.IDS (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12061_12062 ON PUBLIC.LISTEITEM (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12065_12066 ON PUBLIC."MONTH" (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12076_12077 ON PUBLIC.SESSION (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12095_12096 ON PUBLIC.TASK (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_SYS_PK_12115_12116 ON PUBLIC.WEEK (ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_2XFL8878EF9MB38LBDE8AMXEV_12127 ON PUBLIC.BASE_LISTEITEM (LEARN_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_3GGVN6O0IWPKCSNRCXI776G8R_12138 ON PUBLIC.DAY_LISTEITEM (TODOLIST_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_54F0RDG0JYQ5ORD3E161IOVO6_12131 ON PUBLIC.BASEDATE_EVENT (EVENTS_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_5CE86XERY2VJN7X52STWWLUO5_12161 ON PUBLIC.USER_TOKEN (TOKENS_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_777EO64XAISXPFFR2O7AWN0YK_12150 ON PUBLIC.SESSION_GOAL (GOALS_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_7N6YP5QXXNTMUKLUH0UR9IHVB_12134 ON PUBLIC.DAY_LISTEITEM (TODOLISTALL_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_DUF8T6I7AP18AUGVUFW0U7XOR_12167 ON PUBLIC.WEEK_DAY (DAYS_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_IG2906O57SVRHAIM87QTWVIHK_12148 ON PUBLIC.SESSION (NAME);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_J752MVQDGO4PW8VNXMJUE98XR_12123 ON PUBLIC.BASE_LISTEITEM (WILL_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_JGUP1C65J9SM6ONR7ORGN780L_12142 ON PUBLIC.GOAL_LISTEITEM (HOW_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_NCOX90B0NOTK47QW15FMRVRLX_12153 ON PUBLIC.SESSION_MONTH (MONTHS_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_NPB36UEHNE5AVG79QFXETEYVQ_12145 ON PUBLIC.MONTH_WEEK (WEEKS_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_OB8KQYQQGMEFL0ACO34AKDTPE_10095 ON PUBLIC."USER" (EMAIL);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_S95L0N3FIRIQ42YVG1M1T6XF0_12164 ON PUBLIC.USERINFO_SESSION (SESS_ID);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_SB8BBOUER5WAK8VYIIY4PF2BX_10096 ON PUBLIC."USER" (USERNAME);

CREATE UNIQUE INDEX PUBLIC.SYS_IDX_UK_VXVF3H6IAVTE3XJTOKEKUG04_12156 ON PUBLIC.SESSION_TASK (TASKS_ID);

